name: bright sparks
favicon: null
layout_spectrum: 0.3601704831235111
typography_spectrum: 0.5653880392201245
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.36063547409139574
  lightness: 0.8805735055357218
  saturation: 0.7462569314520806
  rhythmicContrast: 0.40484976791776717
purpose: []
